name: Publish to GitHub Pages

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build:prod
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}