name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build:prod
      - name: Package Assets
        run: npm run assets
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: tweakpane-plugin-graph-*.zip
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Create Release
        uses: Roang-zero1/github-create-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v3
        with:
          args: tweakpane-plugin-graph-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}